# Generated by cloudcoil-model-codegen; DO NOT EDIT
from importlib import import_module
from typing import TYPE_CHECKING, Literal, overload

from cloudcoil.resources import Resource

if TYPE_CHECKING:
    from cloudcoil.models.contour.v1 import HTTPProxy as _Resource3
    from cloudcoil.models.contour.v1 import TLSCertificateDelegation as _Resource4
    from cloudcoil.models.contour.v1alpha1 import ContourConfiguration as _Resource0
    from cloudcoil.models.contour.v1alpha1 import ContourDeployment as _Resource1
    from cloudcoil.models.contour.v1alpha1 import ExtensionService as _Resource2

_MODELS = {
    ("ContourConfiguration", "projectcontour.io/v1alpha1"): (
        "cloudcoil.models.contour.v1alpha1",
        "ContourConfiguration",
    ),
    ("ContourConfiguration", ""): ("cloudcoil.models.contour.v1alpha1", "ContourConfiguration"),
    ("ContourDeployment", "projectcontour.io/v1alpha1"): (
        "cloudcoil.models.contour.v1alpha1",
        "ContourDeployment",
    ),
    ("ContourDeployment", ""): ("cloudcoil.models.contour.v1alpha1", "ContourDeployment"),
    ("ExtensionService", "projectcontour.io/v1alpha1"): (
        "cloudcoil.models.contour.v1alpha1",
        "ExtensionService",
    ),
    ("ExtensionService", ""): ("cloudcoil.models.contour.v1alpha1", "ExtensionService"),
    ("HTTPProxy", "projectcontour.io/v1"): ("cloudcoil.models.contour.v1", "HTTPProxy"),
    ("HTTPProxy", ""): ("cloudcoil.models.contour.v1", "HTTPProxy"),
    ("TLSCertificateDelegation", "projectcontour.io/v1"): (
        "cloudcoil.models.contour.v1",
        "TLSCertificateDelegation",
    ),
    ("TLSCertificateDelegation", ""): ("cloudcoil.models.contour.v1", "TLSCertificateDelegation"),
}


@overload
def get_model(
    kind: Literal["ContourConfiguration"], *, api_version: Literal["projectcontour.io/v1alpha1"]
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["ContourConfiguration"], *, api_version: Literal[""] = ""
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["ContourDeployment"], *, api_version: Literal["projectcontour.io/v1alpha1"]
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["ContourDeployment"], *, api_version: Literal[""] = ""
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["ExtensionService"], *, api_version: Literal["projectcontour.io/v1alpha1"]
) -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["ExtensionService"], *, api_version: Literal[""] = ""
) -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["HTTPProxy"], *, api_version: Literal["projectcontour.io/v1"]
) -> type[_Resource3]: ...


@overload
def get_model(kind: Literal["HTTPProxy"], *, api_version: Literal[""] = "") -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["TLSCertificateDelegation"], *, api_version: Literal["projectcontour.io/v1"]
) -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["TLSCertificateDelegation"], *, api_version: Literal[""] = ""
) -> type[_Resource4]: ...


@overload
def get_model(kind: str, *, api_version: str = "") -> type[Resource]: ...


def get_model(kind: str, *, api_version: str = "") -> type[Resource]:
    """Look up a model in this package; specify api_version for ambiguous kinds."""
    try:
        module, name = _MODELS[kind, api_version]
    except KeyError:
        raise ValueError(
            f"Unknown or ambiguous resource {kind!r}; specify a supported api_version"
        ) from None
    return getattr(import_module(module), name)
